[graph]
all-features = true

[advisories]
ignore = []

[licenses]
allow = [
    "GPL-3.0-or-later",
]
confidence-threshold = 0.93

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
