#!/usr/bin/env python3
"""Regenerate src/lib/format/parity-fixtures.json from the Python originals.

Usage: python3 scripts/generate-parity-fixtures.py /path/to/checkout/of/main

The Python app lives on the `main` branch, not on this one, so a separate
checkout (or worktree) of `main` is required. Runs headless: tkinter is
stubbed because the formatter modules import GUI modules at module level.

Case selection avoids exact decimal-rounding ties (e.g. 0.25 → ".1f"):
Python rounds half-to-even, JS toFixed rounds half away from zero. That
divergence is deliberate and pinned by a dedicated test in format.test.ts,
not by these fixtures.
"""

import json
import os
import sys
import types
from collections import namedtuple


def stub_tkinter() -> None:
    tk = types.ModuleType("tkinter")

    class _Stub:
        pass

    tk.Tk = tk.Widget = tk.Toplevel = _Stub
    tk.TclError = Exception
    tk.__getattr__ = lambda n: _Stub
    for name in ["ttk", "font", "filedialog", "messagebox", "scrolledtext"]:
        sub = types.ModuleType(f"tkinter.{name}")
        sub.__getattr__ = lambda n: _Stub
        sys.modules[f"tkinter.{name}"] = sub
        setattr(tk, name, sub)
    sys.modules["tkinter"] = tk


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    repo = sys.argv[1]
    sys.path.insert(0, repo)
    stub_tkinter()

    from src.gui.tabs.history_tab import compute_history_display_values
    from src.gui.tree_display import format_stream_display
    from src.gui.tree_formatters import format_compact_time, format_efficiency
    from src.models import FileRecord, FileStatus
    from src.utils import format_crf, format_file_size, format_time

    audio = namedtuple("A", "codec")

    def history_col(index: int, **kwargs) -> str:
        """Run the real History-tab column computation and pick one cell."""
        record = FileRecord(
            path_hash="0" * 16,
            original_path=None,
            status=kwargs.pop("status", FileStatus.SCANNED),
            file_size_bytes=0,
            file_mtime=0.0,
            **kwargs,
        )
        return compute_history_display_values(record)[index]

    fx = {
        "_source": (
            "generated by scripts/generate-parity-fixtures.py from "
            "src/gui/tree_formatters.py, src/utils.py, src/gui/tree_display.py, "
            "src/gui/tabs/history_tab.py on main"
        )
    }
    fx["formatCompactTime"] = [
        {"seconds": s, "confidence": c, "expected": format_compact_time(s, confidence=c)}
        for s in [0, 1, 30, 59, 60, 61, 90, 3599, 3600, 3661, 7200, 8100, 86399, 359999]
        for c in ["none", "high", "precise", "medium", "low"]
    ]
    fx["formatEfficiency"] = [
        {"savingsBytes": s, "timeSeconds": t, "expected": format_efficiency(s, t)}
        for s, t in [
            (0, 100),
            (1073741824, 0),
            (1073741824, 3600),
            (2684354560, 3600),
            (5368709120, 3600),
            (10737418240, 3600),
            (10737418240, 3599),
            (1234567890, 5432),
            (429496730, 7200),
            (107374182400, 3600),
            (1073741824, 360000),
        ]
    ]
    fx["formatTime"] = [
        {"seconds": s, "expected": format_time(s)}
        for s in [0, 5, 59, 60, 65, 3599, 3600, 3665, 7325, 86400, 90061]
    ]
    fx["formatFileSize"] = [
        {"sizeBytes": b, "expected": format_file_size(b)}
        for b in [
            0, 1, 512, 1023, 1024, 1536, 1048575, 1048576, 5242880, 123456789,
            1073741823, 1073741824, 5368709120, 123456789012, 1099511627776,
        ]
    ]
    fx["formatCrf"] = [{"crf": None, "expected": format_crf(None)}] + [
        {"crf": c, "expected": format_crf(float(c))}
        for c in [0, 23, 23.25, 23.5, 30.75, 45.5, 63]
    ]
    fx["formatStreamDisplay"] = [
        {
            "videoCodec": v,
            "audioCodecs": a,
            "expected": format_stream_display(v, [audio(codec=x) for x in a], 0),
        }
        for v, a in [
            ("h264", ["aac"]),
            ("hevc", ["aac", "ac3"]),
            ("h264", ["aac", "ac3", "dts"]),
            ("h264", ["aac"] * 4),
            ("av1", []),
            (None, ["opus"]),
            ("mpeg4", ["aac"] * 6),
            (None, []),
        ]
    ]

    # History-tab columns (values tuple: 0 date, 2 resolution, 4 bitrate,
    # 6 audio, 9 reduction, 10 vmaf). Date is excluded: the Python column
    # slices an ISO string while the TS formatter takes epoch milliseconds.
    fx["formatResolution"] = [
        {"width": w, "height": h, "expected": history_col(2, width=w, height=h)}
        for w, h in [
            (1920, 1080), (1280, 720), (3840, 2160), (720, 480), (608, 1080),
            (None, None), (1920, None), (None, 1080), (0, 0),
        ]
    ]
    fx["formatBitrate"] = [
        {"kbps": k, "expected": history_col(4, bitrate_kbps=k)}
        for k in [None, 0, 1, 96.4, 850, 999.4, 1000, 1543.2, 4200, 8543.2, 25000]
    ]
    fx["formatAudioCodecs"] = [
        {"audioCodecs": a, "expected": history_col(6, audio_streams=[audio(codec=c) for c in a])}
        for a in [[], ["aac"], ["aac", "ac3"], ["aac", "ac3", "dts"], ["aac"] * 4, ["opus"] * 6]
    ]
    fx["formatReductionPercent"] = [
        {
            "percent": p,
            "expected": history_col(9, status=FileStatus.CONVERTED, reduction_percent=p),
        }
        for p in [None, 0, 0.04, 7.5, 33.333, 45.26, 66.6667, 99.94, 100]
    ]
    fx["formatVmaf"] = [
        {"score": v, "expected": history_col(10, status=FileStatus.CONVERTED, final_vmaf=v)}
        for v in [None, 0, 89.94, 90, 93.333, 95.06, 99.99, 100]
    ]

    out = os.path.join(os.path.dirname(__file__), "..", "src", "lib", "format", "parity-fixtures.json")
    with open(out, "w", encoding="utf-8") as f:
        json.dump(fx, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print("cases:", sum(len(v) for v in fx.values() if isinstance(v, list)))


if __name__ == "__main__":
    main()
