// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**
	 *  Open a native picker off the webview boundary. Cancellation is an accepted
	 *  empty list; errors remain reserved for command/bridge failures.
	 */
	pickPaths: (kind: PathPickerKind, startingDirectory: string | null) => typedError<string[], CommandError>(__TAURI_INVOKE("pick_paths", { kind, startingDirectory })),
	subscribe: (channel: Channel<ShellEvent_Deserialize>) => typedError<null, CommandError>(__TAURI_INVOKE("subscribe", { channel })),
	/**
	 *  Adds files and folders in one batch: folders expand through the engine
	 *  scanner (filtered by the configured scan extensions), directly selected
	 *  files pass through unfiltered. The outcome arrives as one
	 *  `QueueAddSummary` on the stream.
	 */
	queueAddPaths: (inputs: string[], operation: Operation, intent: AnalysisIntent, outputTarget: OutputTarget) => typedError<null, CommandError>(__TAURI_INVOKE("queue_add_paths", { inputs, operation, intent, outputTarget })),
	queueRemove: (itemId: QueueItemId) => typedError<null, CommandError>(__TAURI_INVOKE("queue_remove", { itemId })),
	queueMove: (itemId: QueueItemId, before: number | null) => typedError<null, CommandError>(__TAURI_INVOKE("queue_move", { itemId, before })),
	/**
	 *  Atomically replace the complete pending Queue order. The reducer rejects
	 *  stale or incomplete permutations without exposing intermediate moves.
	 */
	queueReorderPending: (pendingOrder: QueueItemId[]) => typedError<null, CommandError>(__TAURI_INVOKE("queue_reorder_pending", { pendingOrder })),
	queueClear: () => typedError<null, CommandError>(__TAURI_INVOKE("queue_clear")),
	queueClearCompleted: () => typedError<null, CommandError>(__TAURI_INVOKE("queue_clear_completed")),
	queueRetry: (itemId: QueueItemId) => typedError<null, CommandError>(__TAURI_INVOKE("queue_retry", { itemId })),
	queueEdit: (itemId: QueueItemId, patch: QueueItemEdit) => typedError<null, CommandError>(__TAURI_INVOKE("queue_edit", { itemId, patch })),
	start: () => typedError<null, CommandError>(__TAURI_INVOKE("start")),
	stopAfterCurrent: () => typedError<null, CommandError>(__TAURI_INVOKE("stop_after_current")),
	forceStop: () => typedError<null, CommandError>(__TAURI_INVOKE("force_stop")),
	setSettings: (settings: Settings) => typedError<null, CommandError>(__TAURI_INVOKE("set_settings", { settings })),
	vendorInstall: () => typedError<null, CommandError>(__TAURI_INVOKE("vendor_install")),
	vendorCheck: () => typedError<null, CommandError>(__TAURI_INVOKE("vendor_check")),
	/**
	 *  Ask for a fresh Statistics computation. The ack only confirms acceptance;
	 *  the payload arrives as a sequenced `Statistics` ephemeral on the stream
	 *  and is never replayed — re-request after (re)subscribing.
	 */
	requestStatistics: (utcOffsetMinutes: number) => typedError<null, CommandError>(__TAURI_INVOKE("request_statistics", { utcOffsetMinutes })),
	/**
	 *  Import a history file produced by the V2 converter script
	 *  (`docs/HISTORY_IMPORT.md`). Records are parked durably and adopted as
	 *  matching files are prepared.
	 */
	importHistory: (path: string) => typedError<ImportSummary, CommandError>(__TAURI_INVOKE("import_history", { path })),
	/**
	 *  Anonymize every existing log file in place (Settings tab "Scrub Logs").
	 *  Irreversible; runs even when the anonymize-logs toggle is off.
	 */
	scrubLogs: () => typedError<ScrubSummary, CommandError>(__TAURI_INVOKE("scrub_logs")),
	/**
	 *  One-shot manual check of the GitHub releases API (#33 §12: no background
	 *  checking exists). Async so the blocking network call never runs on the
	 *  main thread; the release page URL stays shell-side — open it with
	 *  `open_release_page`.
	 */
	checkForUpdate: () => typedError<ReleaseSummary, CommandError>(__TAURI_INVOKE("check_for_update")),
	/**  Open the release page recorded by the last successful `check_for_update`. */
	openReleasePage: () => typedError<null, CommandError>(__TAURI_INVOKE("open_release_page")),
	/**
	 *  Consent to discard a corrupt journal tail. The signature must echo the
	 *  one delivered on the `Degraded` payload — the driver rejects anything
	 *  else, so a stale acknowledgement can never discard fresher bytes.
	 */
	acknowledgeCorruption: (signature: CorruptionSignature) => typedError<null, CommandError>(__TAURI_INVOKE("acknowledge_corruption", { signature })),
	/**
	 *  Opens a file or folder with the operating system's default program.
	 * 
	 *  Which path to act on (input, converted output) is frontend state, so the
	 *  path arrives explicitly. No domain state is involved: the call goes
	 *  straight to the engine, bypassing the reducer. Declared async so the
	 *  desktop hand-off (which can stall on a misbehaving handler) runs off the
	 *  main thread.
	 */
	openPath: (path: string) => typedError<null, CommandError>(__TAURI_INVOKE("open_path", { path })),
	/**
	 *  Reveals a path selected in the system file manager. Same contract as
	 *  [`open_path`].
	 */
	revealInFileManager: (path: string) => typedError<null, CommandError>(__TAURI_INVOKE("reveal_in_file_manager", { path })),
};

/* Types */
export type AnalysisActivity = "Discovering" | "Discovered" | "BasicScanning" | "Ready" | "Cancelled" | { Failed: {
	detail: string,
} };

export type AnalysisAttempt = {
	target: VmafTarget,
	last_measurement: SearchMeasurement | null,
};

/**
 *  Bounded live changes plus the complete replacement used at generation
 *  start and reconnect. Consumers apply this through [`fold_analysis`].
 */
export type AnalysisDelta = AnalysisDelta_Serialize | AnalysisDelta_Deserialize;

/**
 *  Bounded live changes plus the complete replacement used at generation
 *  start and reconnect. Consumers apply this through [`fold_analysis`].
 */
export type AnalysisDelta_Deserialize = ({ Reset: {
	snapshot: AnalysisSnapshot_Deserialize,
} }) & { ActivityChanged?: never; RowsUpserted?: never } | ({ RowsUpserted: {
	generation: AnalysisGenerationId,
	rows: AnalysisRow[],
} }) & { ActivityChanged?: never; Reset?: never } | ({ ActivityChanged: {
	generation: AnalysisGenerationId,
	activity: AnalysisActivity,
} }) & { Reset?: never; RowsUpserted?: never };

/**
 *  Bounded live changes plus the complete replacement used at generation
 *  start and reconnect. Consumers apply this through [`fold_analysis`].
 */
export type AnalysisDelta_Serialize = ({ Reset: {
	snapshot: AnalysisSnapshot_Serialize,
} }) & { ActivityChanged?: never; RowsUpserted?: never } | ({ RowsUpserted: {
	generation: AnalysisGenerationId,
	rows: AnalysisRow[],
} }) & { ActivityChanged?: never; Reset?: never } | ({ ActivityChanged: {
	generation: AnalysisGenerationId,
	activity: AnalysisActivity,
} }) & { Reset?: never; RowsUpserted?: never };

/**
 *  Presentation text derived from a native path. `lossy` is explicit so the
 *  UI never mistakes a replacement-character rendering for a reversible path.
 */
export type AnalysisDisplayText = {
	text: string,
	lossy: boolean,
};

export type AnalysisEntryKind = "Folder" | "File";

/**
 *  One generation's standing public state. Native paths and execution
 *  handles deliberately live in the engine's generation registry instead.
 */
export type AnalysisGeneration = AnalysisGeneration_Serialize | AnalysisGeneration_Deserialize;

export type AnalysisGenerationId = number;

/**
 *  One generation's standing public state. Native paths and execution
 *  handles deliberately live in the engine's generation registry instead.
 */
export type AnalysisGeneration_Deserialize = {
	id: AnalysisGenerationId,
	root: AnalysisDisplayText,
	activity: AnalysisActivity,
	rows: AnalysisRow[],
};

/**
 *  One generation's standing public state. Native paths and execution
 *  handles deliberately live in the engine's generation registry instead.
 */
export type AnalysisGeneration_Serialize = {
	id: AnalysisGenerationId,
	root: AnalysisDisplayText,
	activity: AnalysisActivity,
	rows: AnalysisRow[],
};

/**
 *  Whether a queued item may reuse a durable analysis that already satisfies
 *  its execution settings. `Refresh` forces a fresh search even when a cached
 *  result qualifies; the new result still lands in the record's analysis
 *  index like any other.
 */
export type AnalysisIntent = "ReuseIfFresh" | "Refresh";

export type AnalysisProfile = {
	preset: number,
	max_encoded_percent_basis_points: number,
	samples: number | null,
	sample_duration_ms: number,
	thorough: boolean,
	/**
	 *  The decode mode the search actually ran with — part of the analysis
	 *  identity (ADR-007, per #33 §7): hardware and software decoders can
	 *  produce different decoded frames, so their VMAF measurements are not
	 *  interchangeable. The pin is decoder-granular: a Cuvid-recorded
	 *  analysis is not returned for a Qsv execution and re-searches instead.
	 *  Requested-vs-actual provenance lives on the run (`decode_preference`,
	 *  this field, and the terminal evidence's `encode_decode`).
	 */
	decode_mode: DecodeMode,
	ab_av1_revision: string,
	ffmpeg_revision: string,
	encoder_revision: string,
};

export type AnalysisResult = {
	requested_target: VmafTarget,
	successful_target: VmafTarget,
	fallback_floor: VmafTarget,
	fallback_step: number,
	failed_attempts: AnalysisAttempt[],
	measurement: SearchMeasurement,
	profile: AnalysisProfile,
};

/**
 *  Level-0 row facts only. Media facts, applicability, predictions, and
 *  failures extend the Analysis read model in their owning child issues.
 */
export type AnalysisRow = {
	id: AnalysisRowId,
	parent: AnalysisRowId | null,
	kind: AnalysisEntryKind,
	display_name: AnalysisDisplayText,
	display_path: AnalysisDisplayText,
};

export type AnalysisRowId = number;

/**
 *  Standing Analysis state. It is reducer-owned and replayed on subscribe,
 *  but never enters the durable application snapshot or journal.
 */
export type AnalysisSnapshot = AnalysisSnapshot_Serialize | AnalysisSnapshot_Deserialize;

/**
 *  Standing Analysis state. It is reducer-owned and replayed on subscribe,
 *  but never enters the durable application snapshot or journal.
 */
export type AnalysisSnapshot_Deserialize = {
	current: AnalysisGeneration_Deserialize | null,
};

/**
 *  Standing Analysis state. It is reducer-owned and replayed on subscribe,
 *  but never enters the durable application snapshot or journal.
 */
export type AnalysisSnapshot_Serialize = {
	current: AnalysisGeneration_Serialize | null,
};

export type AppInfo = {
	version: string,
};

export type AppSnapshot = AppSnapshot_Serialize | AppSnapshot_Deserialize;

export type AppSnapshot_Deserialize = {
	durable: DurableState_Deserialize,
	settings: Settings,
};

export type AppSnapshot_Serialize = {
	durable: DurableState_Serialize,
	settings: Settings,
};

export type ArtifactIdentity = ArtifactIdentity_Serialize | ArtifactIdentity_Deserialize;

export type ArtifactIdentity_Deserialize = {
	content_key: ContentKey,
	destructive: DestructiveIdentity_Deserialize,
};

export type ArtifactIdentity_Serialize = {
	content_key: ContentKey,
	destructive: DestructiveIdentity_Serialize,
};

export type AudioCodec = "Aac" | "Ac3" | "Eac3" | "Dts" | "Opus" | "Flac" | "Mp3" | { Other: string };

/**
 *  One audio stream of the inspected file. Consumers are remux-eligibility
 *  policy and remux reporting, not the current view designs, so this stays a
 *  summary rather than a full stream description.
 */
export type AudioStreamMeta = {
	codec: AudioCodec,
	channels: number,
};

export type ClaimId = number;

export type CodecCount = {
	codec: VideoCodec,
	count: number,
};

export type CommandError = {
	code: string,
	message: string,
};

/**
 *  Where the facts backing a successful outcome came from. A live run carries
 *  what the adapter measured; a crash-recovered success carries nothing —
 *  output size, path, and content key are already durable on the settled
 *  transaction, and fabricating adapter fields would be dishonest.
 */
export type CompletionEvidence = ({ LiveEncode: {
	input_size: number,
	output_size: number,
	stream_sizes: StreamByteSizes,
	/**
	 *  The decode mode the encode actually ran with; diverges from the
	 *  analysis profile once the hardware→software retry ladder exists.
	 */
	encode_decode: DecodeMode,
} }) & { LiveRemux?: never } | ({ LiveRemux: {
	input_size: number,
	output_size: number,
} }) & { LiveEncode?: never } | "RecoveredAtStartup";

export type ConfigDelta = { SettingsChanged: {
	settings: Settings,
} };

/**
 *  Why an output transaction settled as a conflict. `IdentityMismatch` means
 *  observed files no longer match the ledger; `InspectionFailed` means the
 *  filesystem could not be inspected or acted on to find out.
 */
export type ConflictKind = "IdentityMismatch" | "InspectionFailed";

export type ContentKey = string;

export type ConversionRun = {
	spec: JobSpec,
	analysis: AnalysisResult | null,
	output_content_key: ContentKey | null,
	/**
	 *  Mirrors the owning queue item's `QueueItemState::Finished(outcome)`;
	 *  both are written by the single `DurableDelta::ItemFinished` fold arm.
	 *  The run keeps its own copy because it outlives the queue item (items
	 *  can be removed once finished) and because journal replay uses
	 *  `outcome.is_some()` as its "run already terminal" guard. Projections
	 *  must not let the two diverge.
	 */
	outcome: ItemOutcome | null,
	started_at: UnixMillis | null,
	finished_at: UnixMillis | null,
	phase_spans: PhaseSpan[],
};

/**
 *  The degraded surface shown to the operator: why replay stopped, and the
 *  identity of the unreadable bytes an acknowledgement would discard.
 */
export type CorruptionReport = {
	reason: string,
	signature: CorruptionSignature,
};

/**
 *  Identity of a journal's unreadable suffix: everything past the last
 *  replayable record. An acknowledgement quotes this signature back, so
 *  recovery only ever discards the exact bytes the operator was shown — a
 *  journal that changed since the report was produced yields a different
 *  signature and the acknowledgement is rejected.
 */
export type CorruptionSignature = {
	/**  Byte length of the unreadable suffix. */
	tail_len: number,
	/**  Hex BLAKE2b-512 digest of the unreadable suffix bytes. */
	digest: string,
};

export type Crf = number;

/**
 *  One point of the cumulative savings series: a local calendar day (days
 *  since the Unix epoch in the requester's timezone) and the running total
 *  through that day. The series can dip when an output grew.
 */
export type CumulativeSavingsPoint = {
	epoch_day: number,
	cumulative_saved_bytes: number,
};

export type DecodeMode = "Software" | { Hardware: HardwareDecoder };

export type DecodePreference = "SoftwareOnly" | "HardwarePreferred";

export type DefaultOutputMode = "replace" | "suffix" | "separate_folder";

export type DestructiveIdentity = DestructiveIdentity_Serialize | DestructiveIdentity_Deserialize;

export type DestructiveIdentity_Deserialize = {
	file_id: FileSystemId_Deserialize,
	size: number,
	modified_ns: FileTimeNs | null,
};

export type DestructiveIdentity_Serialize = {
	file_id: FileSystemId_Serialize,
	size: number,
	modified_ns: FileTimeNs | null,
};

/**
 *  Bounded diagnostic text journaled with a failure — typically the tail of a
 *  process's stderr. Producers must substitute run paths with placeholders
 *  before construction; the durable model never sees a real path here.
 * 
 *  Deliberately no `Display` impl: the tail is payload for inspection surfaces,
 *  not prose to be interpolated into messages.
 */
export type DiagnosticTail = string;

export type DurableDelta = DurableDelta_Serialize | DurableDelta_Deserialize;

export type DurableDelta_Deserialize = ({ QueueAdded: {
	item: QueueItem,
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | ({ QueueRemoved: {
	item_id: QueueItemId,
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueReordered?: never; QueueRequeued?: never } | ({ QueueMoved: {
	item_id: QueueItemId,
	before: QueueItemId | null,
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | 
/**
 *  Atomically replaces the order of the complete queued tail. Finished
 *  and active items keep their positions in the frozen prefix.
 */
({ QueueReordered: {
	pending_order: QueueItemId[],
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueRequeued?: never } | 
/**
 *  A finished item goes around again: state resets to `Queued` and the
 *  item moves to the end of the queue, preserving the
 *  finished < active < queued shape invariant. The old run's lineage is
 *  untouched; fresh claim/run ids arrive at the next reservation.
 */
({ QueueRequeued: {
	item_id: QueueItemId,
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never } | 
/**
 *  A pending item's job parameters, resolved to the full tuple so the
 *  fold stays structural and replay needs no patch semantics.
 */
({ QueueEdited: {
	item_id: QueueItemId,
	operation: Operation,
	intent: AnalysisIntent,
	output_target: OutputTarget,
	overwrite: OverwriteDecision,
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | ({ ItemReserved: {
	job: ReservedJob,
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | ({ MediaObserved: {
	observation: MediaObservation_Deserialize,
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | ({ ItemPrepared: {
	spec: JobSpec,
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | ({ ItemRunning: {
	item_id: QueueItemId,
	claim_id: ClaimId,
	run_id: RunId,
	at: UnixMillis,
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | ({ AnalysisRecorded: {
	run_id: RunId,
	result: AnalysisResult,
} }) & { HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | ({ ItemFinished: {
	item_id: QueueItemId,
	claim_id: ClaimId,
	run_id: RunId,
	outcome: ItemOutcome,
	at: UnixMillis,
	phase_spans: PhaseSpan[],
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | ({ Output: OutputDelta_Deserialize }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | 
/**
 *  An import batch landing in the parked inbox. One delta per accepted
 *  import; the reducer has already dropped keys that are parked or
 *  adopted.
 */
({ HistoryImported: {
	records: ([ImportPath, ImportedHistoryRecord])[],
} }) & { AnalysisRecorded?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | 
/**
 *  A parked record matched the observed file: the parked entry leaves
 *  the inbox, the content record gains import provenance, and — when the
 *  resolution decided one — an adopted verdict.
 */
({ ParkedAdopted: {
	import_path: ImportPath,
	content_key: ContentKey,
	imported: ImportedHistoryRecord,
	verdict: Verdict | null,
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | 
/**
 *  A parked record no longer describes the file at its path: stale
 *  content, retired without adoption. Durable so replay converges and the
 *  journal keeps an audit trail of every discarded imported claim.
 */
({ ParkedRetired: {
	import_path: ImportPath,
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never };

export type DurableDelta_Serialize = ({ QueueAdded: {
	item: QueueItem,
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | ({ QueueRemoved: {
	item_id: QueueItemId,
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueReordered?: never; QueueRequeued?: never } | ({ QueueMoved: {
	item_id: QueueItemId,
	before: QueueItemId | null,
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | 
/**
 *  Atomically replaces the order of the complete queued tail. Finished
 *  and active items keep their positions in the frozen prefix.
 */
({ QueueReordered: {
	pending_order: QueueItemId[],
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueRequeued?: never } | 
/**
 *  A finished item goes around again: state resets to `Queued` and the
 *  item moves to the end of the queue, preserving the
 *  finished < active < queued shape invariant. The old run's lineage is
 *  untouched; fresh claim/run ids arrive at the next reservation.
 */
({ QueueRequeued: {
	item_id: QueueItemId,
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never } | 
/**
 *  A pending item's job parameters, resolved to the full tuple so the
 *  fold stays structural and replay needs no patch semantics.
 */
({ QueueEdited: {
	item_id: QueueItemId,
	operation: Operation,
	intent: AnalysisIntent,
	output_target: OutputTarget,
	overwrite: OverwriteDecision,
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | ({ ItemReserved: {
	job: ReservedJob,
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | ({ MediaObserved: {
	observation: MediaObservation_Serialize,
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | ({ ItemPrepared: {
	spec: JobSpec,
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | ({ ItemRunning: {
	item_id: QueueItemId,
	claim_id: ClaimId,
	run_id: RunId,
	at: UnixMillis,
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | ({ AnalysisRecorded: {
	run_id: RunId,
	result: AnalysisResult,
} }) & { HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | ({ ItemFinished: {
	item_id: QueueItemId,
	claim_id: ClaimId,
	run_id: RunId,
	outcome: ItemOutcome,
	at: UnixMillis,
	phase_spans: PhaseSpan[],
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | ({ Output: OutputDelta_Serialize }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | 
/**
 *  An import batch landing in the parked inbox. One delta per accepted
 *  import; the reducer has already dropped keys that are parked or
 *  adopted.
 */
({ HistoryImported: {
	records: ([ImportPath, ImportedHistoryRecord])[],
} }) & { AnalysisRecorded?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | 
/**
 *  A parked record matched the observed file: the parked entry leaves
 *  the inbox, the content record gains import provenance, and — when the
 *  resolution decided one — an adopted verdict.
 */
({ ParkedAdopted: {
	import_path: ImportPath,
	content_key: ContentKey,
	imported: ImportedHistoryRecord,
	verdict: Verdict | null,
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedRetired?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never } | 
/**
 *  A parked record no longer describes the file at its path: stale
 *  content, retired without adoption. Durable so replay converges and the
 *  journal keeps an audit trail of every discarded imported claim.
 */
({ ParkedRetired: {
	import_path: ImportPath,
} }) & { AnalysisRecorded?: never; HistoryImported?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; ParkedAdopted?: never; QueueAdded?: never; QueueEdited?: never; QueueMoved?: never; QueueRemoved?: never; QueueReordered?: never; QueueRequeued?: never };

export type DurableState = DurableState_Serialize | DurableState_Deserialize;

export type DurableState_Deserialize = {
	queue: QueueItem[],
	paths: { [key in PathHash]: PathBinding_Deserialize },
	records: { [key in ContentKey]: FileRecord_Deserialize },
	outputs: { [key in RunId]: OutputTransaction_Deserialize },
	conversion_runs: { [key in RunId]: ConversionRun },
	/**
	 *  Imported history records not yet matched to a real file. The inbox
	 *  empties itself: prepare-time adoption or retirement removes entries;
	 *  nothing else writes here after an import.
	 */
	parked: { [key in ImportPath]: ImportedHistoryRecord },
	/**
	 *  Every successfully adopted normalized path. This is the complete
	 *  re-import guard; collision losers remain here even though a content
	 *  record retains only one imported summary.
	 */
	adopted_imports: ImportPath[],
};

export type DurableState_Serialize = {
	queue: QueueItem[],
	paths: { [key in PathHash]: PathBinding_Serialize },
	records: { [key in ContentKey]: FileRecord_Serialize },
	outputs: { [key in RunId]: OutputTransaction_Serialize },
	conversion_runs: { [key in RunId]: ConversionRun },
	/**
	 *  Imported history records not yet matched to a real file. The inbox
	 *  empties itself: prepare-time adoption or retirement removes entries;
	 *  nothing else writes here after an import.
	 */
	parked: { [key in ImportPath]: ImportedHistoryRecord },
	/**
	 *  Every successfully adopted normalized path. This is the complete
	 *  re-import guard; collision losers remain here even though a content
	 *  record retains only one imported summary.
	 */
	adopted_imports: ImportPath[],
};

/**  A duration in milliseconds, measured engine-side with a monotonic clock. */
export type DurationMs = number;

export type EphemeralDelta = EphemeralDelta_Serialize | EphemeralDelta_Deserialize;

export type EphemeralDelta_Deserialize = 
/**
 *  Incremental or replacement Analysis read-model state. Standing: the
 *  shell folds it and replays one complete Reset on every subscription.
 */
({ Analysis: AnalysisDelta_Deserialize }) & { CommandRejected?: never; QueueAddSummary?: never; SessionAggregates?: never; SessionChanged?: never; Statistics?: never; Telemetry?: never; TelemetryCleared?: never; ToolsChanged?: never; WorkerCrashed?: never } | ({ SessionChanged: SessionState }) & { Analysis?: never; CommandRejected?: never; QueueAddSummary?: never; SessionAggregates?: never; Statistics?: never; Telemetry?: never; TelemetryCleared?: never; ToolsChanged?: never; WorkerCrashed?: never } | 
/**
 *  The per-session aggregates after an item finished (zeroed at session
 *  start). The one post-durable ephemeral: on the stream it follows the
 *  `ItemFinished` it summarizes, so a consumer never sees counts for a
 *  finish it has not observed.
 */
({ SessionAggregates: SessionAggregates }) & { Analysis?: never; CommandRejected?: never; QueueAddSummary?: never; SessionChanged?: never; Statistics?: never; Telemetry?: never; TelemetryCleared?: never; ToolsChanged?: never; WorkerCrashed?: never } | ({ Telemetry: Telemetry }) & { Analysis?: never; CommandRejected?: never; QueueAddSummary?: never; SessionAggregates?: never; SessionChanged?: never; Statistics?: never; TelemetryCleared?: never; ToolsChanged?: never; WorkerCrashed?: never } | ({ TelemetryCleared: {
	run_id: RunId,
} }) & { Analysis?: never; CommandRejected?: never; QueueAddSummary?: never; SessionAggregates?: never; SessionChanged?: never; Statistics?: never; Telemetry?: never; ToolsChanged?: never; WorkerCrashed?: never } | ({ ToolsChanged: ToolsState }) & { Analysis?: never; CommandRejected?: never; QueueAddSummary?: never; SessionAggregates?: never; SessionChanged?: never; Statistics?: never; Telemetry?: never; TelemetryCleared?: never; WorkerCrashed?: never } | 
/**
 *  Answer to [`ProjectionCommand::RequestStatistics`]. Fire-and-forget:
 *  not part of the read model and never replayed on subscribe.
 */
({ Statistics: StatisticsPayload }) & { Analysis?: never; CommandRejected?: never; QueueAddSummary?: never; SessionAggregates?: never; SessionChanged?: never; Telemetry?: never; TelemetryCleared?: never; ToolsChanged?: never; WorkerCrashed?: never } | ({ WorkerCrashed: {
	message: string,
} }) & { Analysis?: never; CommandRejected?: never; QueueAddSummary?: never; SessionAggregates?: never; SessionChanged?: never; Statistics?: never; Telemetry?: never; TelemetryCleared?: never; ToolsChanged?: never } | ({ CommandRejected: {
	reason: string,
} }) & { Analysis?: never; QueueAddSummary?: never; SessionAggregates?: never; SessionChanged?: never; Statistics?: never; Telemetry?: never; TelemetryCleared?: never; ToolsChanged?: never; WorkerCrashed?: never } | 
/**
 *  Disposition counts for one [`QueueCommand::AddMany`] batch. Reasons
 *  carry their payloads, so distinct payloads (different source runs)
 *  count as separate entries — consumers sum across entries.
 */
({ QueueAddSummary: {
	added: number,
	skipped: ([SkipReason, number])[],
} }) & { Analysis?: never; CommandRejected?: never; SessionAggregates?: never; SessionChanged?: never; Statistics?: never; Telemetry?: never; TelemetryCleared?: never; ToolsChanged?: never; WorkerCrashed?: never };

export type EphemeralDelta_Serialize = 
/**
 *  Incremental or replacement Analysis read-model state. Standing: the
 *  shell folds it and replays one complete Reset on every subscription.
 */
({ Analysis: AnalysisDelta_Serialize }) & { CommandRejected?: never; QueueAddSummary?: never; SessionAggregates?: never; SessionChanged?: never; Statistics?: never; Telemetry?: never; TelemetryCleared?: never; ToolsChanged?: never; WorkerCrashed?: never } | ({ SessionChanged: SessionState }) & { Analysis?: never; CommandRejected?: never; QueueAddSummary?: never; SessionAggregates?: never; Statistics?: never; Telemetry?: never; TelemetryCleared?: never; ToolsChanged?: never; WorkerCrashed?: never } | 
/**
 *  The per-session aggregates after an item finished (zeroed at session
 *  start). The one post-durable ephemeral: on the stream it follows the
 *  `ItemFinished` it summarizes, so a consumer never sees counts for a
 *  finish it has not observed.
 */
({ SessionAggregates: SessionAggregates }) & { Analysis?: never; CommandRejected?: never; QueueAddSummary?: never; SessionChanged?: never; Statistics?: never; Telemetry?: never; TelemetryCleared?: never; ToolsChanged?: never; WorkerCrashed?: never } | ({ Telemetry: Telemetry }) & { Analysis?: never; CommandRejected?: never; QueueAddSummary?: never; SessionAggregates?: never; SessionChanged?: never; Statistics?: never; TelemetryCleared?: never; ToolsChanged?: never; WorkerCrashed?: never } | ({ TelemetryCleared: {
	run_id: RunId,
} }) & { Analysis?: never; CommandRejected?: never; QueueAddSummary?: never; SessionAggregates?: never; SessionChanged?: never; Statistics?: never; Telemetry?: never; ToolsChanged?: never; WorkerCrashed?: never } | ({ ToolsChanged: ToolsState }) & { Analysis?: never; CommandRejected?: never; QueueAddSummary?: never; SessionAggregates?: never; SessionChanged?: never; Statistics?: never; Telemetry?: never; TelemetryCleared?: never; WorkerCrashed?: never } | 
/**
 *  Answer to [`ProjectionCommand::RequestStatistics`]. Fire-and-forget:
 *  not part of the read model and never replayed on subscribe.
 */
({ Statistics: StatisticsPayload }) & { Analysis?: never; CommandRejected?: never; QueueAddSummary?: never; SessionAggregates?: never; SessionChanged?: never; Telemetry?: never; TelemetryCleared?: never; ToolsChanged?: never; WorkerCrashed?: never } | ({ WorkerCrashed: {
	message: string,
} }) & { Analysis?: never; CommandRejected?: never; QueueAddSummary?: never; SessionAggregates?: never; SessionChanged?: never; Statistics?: never; Telemetry?: never; TelemetryCleared?: never; ToolsChanged?: never } | ({ CommandRejected: {
	reason: string,
} }) & { Analysis?: never; QueueAddSummary?: never; SessionAggregates?: never; SessionChanged?: never; Statistics?: never; Telemetry?: never; TelemetryCleared?: never; ToolsChanged?: never; WorkerCrashed?: never } | 
/**
 *  Disposition counts for one [`QueueCommand::AddMany`] batch. Reasons
 *  carry their payloads, so distinct payloads (different source runs)
 *  count as separate entries — consumers sum across entries.
 */
({ QueueAddSummary: {
	added: number,
	skipped: ([SkipReason, number])[],
} }) & { Analysis?: never; CommandRejected?: never; SessionAggregates?: never; SessionChanged?: never; Statistics?: never; Telemetry?: never; TelemetryCleared?: never; ToolsChanged?: never; WorkerCrashed?: never };

export type ExecutionSettings = {
	requested_target: VmafTarget,
	fallback_floor: VmafTarget,
	fallback_step: number,
	overwrite_existing: boolean,
	decode_preference: DecodePreference,
	profile: AnalysisProfile,
};

/**
 *  The durable description of a failed run: a stable kind for policy and
 *  display grouping, a user-facing message, and a bounded diagnostic tail.
 */
export type FailureFacts = {
	kind: FailureKind,
	message: string,
	diagnostic: DiagnosticTail,
};

/**
 *  Which class of work failed. One variant per production failure site class
 *  in the engine coordinator; `Internal` covers protocol and channel errors —
 *  there is no open-ended escape variant.
 */
export type FailureKind = "SearchStart" | "SearchRun" | "EncodeStart" | "EncodeRun" | "RemuxStart" | "RemuxRun" | { AdapterPanicked: {
	cleanup_failed: boolean,
} } | "OutputPrepare" | "OutputPromote" | "OutputConflict" | "Internal";

export type FileRecord = FileRecord_Serialize | FileRecord_Deserialize;

export type FileRecord_Deserialize = {
	metadata: VideoMeta,
	analyses: ([AnalysisProfile, { [key in VmafTarget]: AnalysisResult }])[],
	verdict: Verdict | null,
	/**
	 *  The deterministic imported summary retained for History/Statistics
	 *  continuity. The complete re-import guard lives in
	 *  `DurableState::adopted_imports` because several paths may collapse
	 *  onto one content record.
	 */
	imported: ImportedProvenance | null,
};

export type FileRecord_Serialize = {
	metadata: VideoMeta,
	analyses: ([AnalysisProfile, { [key in VmafTarget]: AnalysisResult }])[],
	verdict: Verdict | null,
	/**
	 *  The deterministic imported summary retained for History/Statistics
	 *  continuity. The complete re-import guard lives in
	 *  `DurableState::adopted_imports` because several paths may collapse
	 *  onto one content record.
	 */
	imported: ImportedProvenance | null,
};

export type FileSystemId = FileSystemId_Serialize | FileSystemId_Deserialize;

export type FileSystemId_Deserialize = ({ Unix: {
	device: number,
	inode: number,
} }) & { WindowsHighResolution?: never; WindowsLowResolution?: never } | ({ WindowsLowResolution: {
	volume_serial: number,
	file_index: number,
} }) & { Unix?: never; WindowsHighResolution?: never } | ({ WindowsHighResolution: {
	volume_serial: number,
	file_id: string,
} }) & { Unix?: never; WindowsLowResolution?: never };

export type FileSystemId_Serialize = ({ Unix: {
	device: number,
	inode: number,
} }) & { WindowsHighResolution?: never; WindowsLowResolution?: never } | ({ WindowsLowResolution: {
	volume_serial: number,
	file_index: number,
} }) & { Unix?: never; WindowsHighResolution?: never } | ({ WindowsHighResolution: {
	volume_serial: number,
	file_id: string,
} }) & { Unix?: never; WindowsLowResolution?: never };

/**
 *  A filesystem modification time in nanoseconds since the Unix epoch.
 *  Serialized as a JSON string: the value routinely exceeds 2^53, which a
 *  JavaScript `number` would silently round. The frontend treats it as opaque.
 */
export type FileTimeNs = string;

export type HardwareDecoder = "H264Cuvid" | "H264Qsv" | "HevcCuvid" | "HevcQsv" | "Vp9Cuvid" | "Vp9Qsv" | "Av1Cuvid" | "Av1Qsv";

/**
 *  One History row per native/adopted content or reportable parked import.
 *  Facts only — units, prefixes, and labels are presentation. Native width
 *  and height are post-rotation. Bitrate is derived in views from size and
 *  duration, matching the [`crate::VideoMeta`] contract.
 */
export type HistoryRow = {
	key: HistoryRowKey,
	status: HistoryStatus,
	source_run: RunId | null,
	happened_at: UnixMillis | null,
	codec: VideoCodec | null,
	container: MediaContainer | null,
	width: number | null,
	height: number | null,
	duration_ms: number | null,
	/**
	 *  `None` means the source did not record audio metadata; `Some([])`
	 *  means probing established that the file has no audio streams.
	 */
	audio: AudioCodec[] | null,
	input_size_bytes: number | null,
	output_size_bytes: number | null,
	encoding_time_ms: number | null,
	vmaf: VmafScore | null,
	crf: Crf | null,
};

/**
 *  Stable identity for either an observed content row or an unresolved
 *  imported path row.
 */
export type HistoryRowKey = { kind: "Content"; value: ContentKey } | { kind: "Parked"; value: ImportPath };

/**  The current standing of one content in History terms. */
export type HistoryStatus = "Converted" | "Remuxed" | ({ NotWorthwhile: {
	requested: VmafTarget,
	floor: VmafTarget,
} }) & { Failed?: never } | "Analyzed" | ({ Failed: {
	kind: FailureKind,
	message: string,
} }) & { NotWorthwhile?: never } | "Stopped";

/**
 *  The normalized source-path key an imported history record is parked
 *  under. Normalization is v3's own documented rule (verbatim prefixes
 *  stripped, backslashes to slashes, lowercased) applied by the engine at
 *  import and at prepare time, so both sides of the match meet on the same
 *  spelling. Cleartext PII — a phase-5 scrub target.
 */
export type ImportPath = string;

/**
 *  Outcome of a history import: how many records were parked and how many
 *  were skipped as duplicates of already-parked or already-adopted paths.
 */
export type ImportSummary = {
	parked: number,
	skipped: number,
};

/**
 *  Historical facts imported from V2. The same value starts in the parked
 *  inbox and, after adoption, may survive as display-only provenance on a
 *  content record.
 *  Every field the import schema marks optional is nullable — the import
 *  carries what the source record actually said, nothing synthesized.
 *  Fixed-point integers only: durable state derives `Eq`, so any float
 *  representation is the converter script's problem, never this crate's.
 */
export type ImportedHistoryRecord = {
	status: ParkedStatus,
	/**
	 *  Byte size of the source file when the record was decided: both the
	 *  freshness-stamp probe and the input size for a converted record's
	 *  summary.
	 */
	size: number | null,
	modified_ns: FileTimeNs | null,
	video_codec: VideoCodec | null,
	width: number | null,
	height: number | null,
	duration_ms: number | null,
	output_size: number | null,
	encoding_time: DurationMs | null,
	crf: Crf | null,
	vmaf: VmafScore | null,
	target: VmafTarget | null,
	requested_target: VmafTarget | null,
	floor_target: VmafTarget | null,
	/**
	 *  When the source record was decided, falling back to the import
	 *  instant when the source carried no timestamp.
	 */
	decided_at: UnixMillis,
};

/**
 *  The one deterministic imported summary retained on a content record.
 *  Every adopted path is guarded separately by `DurableState::adopted_imports`.
 */
export type ImportedProvenance = {
	import_path: ImportPath,
	record: ImportedHistoryRecord,
};

export type ItemOutcome = "Analyzed" | ({ Converted: CompletionEvidence }) & { Failed?: never; NotWorthwhile?: never; Remuxed?: never; Skipped?: never } | ({ Remuxed: CompletionEvidence }) & { Converted?: never; Failed?: never; NotWorthwhile?: never; Skipped?: never } | ({ NotWorthwhile: {
	attempts: AnalysisAttempt[],
} }) & { Converted?: never; Failed?: never; Remuxed?: never; Skipped?: never } | "Stopped" | ({ Skipped: {
	reason: SkipReason,
} }) & { Converted?: never; Failed?: never; NotWorthwhile?: never; Remuxed?: never } | ({ Failed: FailureFacts }) & { Converted?: never; NotWorthwhile?: never; Remuxed?: never; Skipped?: never };

export type JobAction = ({ Analyze: {
	selected_analysis: AnalysisResult | null,
} }) & { Encode?: never; Skip?: never } | ({ Encode: {
	selected_analysis: AnalysisResult | null,
} }) & { Analyze?: never; Skip?: never } | "Remux" | ({ Skip: {
	reason: SkipReason,
} }) & { Analyze?: never; Encode?: never };

export type JobPhase = "Preparing" | "Analyzing" | "Encoding" | "Remuxing" | "Verifying" | "Finalizing";

export type JobProgress = "Phase" | ({ SearchBasisPoints: number }) & { OutputPositionMs?: never } | ({ OutputPositionMs: number }) & { SearchBasisPoints?: never };

export type JobSpec = {
	item_id: QueueItemId,
	claim_id: ClaimId,
	run_id: RunId,
	input: string,
	content_key: ContentKey | null,
	operation: Operation,
	intent: AnalysisIntent,
	output_target: OutputTarget,
	execution: ExecutionSettings,
	action: JobAction,
};

export type MediaContainer = "Matroska" | { Other: string };

export type MediaObservation = MediaObservation_Serialize | MediaObservation_Deserialize;

export type MediaObservation_Deserialize = {
	path_hash: PathHash,
	binding: PathBinding_Deserialize,
	metadata: VideoMeta,
};

export type MediaObservation_Serialize = {
	path_hash: PathHash,
	binding: PathBinding_Serialize,
	metadata: VideoMeta,
};

export type MediaTool = "Ffmpeg" | "Ffprobe";

export type Operation = "Analyze" | "Convert";

export type OutputDelta = OutputDelta_Serialize | OutputDelta_Deserialize;

export type OutputDelta_Deserialize = ({ OutputStarted: {
	transaction: OutputTransaction_Deserialize,
} }) & { AbandonStagingIntent?: never; Abandoned?: never; Conflict?: never; OriginalRetired?: never; OutputCommitted?: never; OutputReady?: never; RetireOriginalIntent?: never; StagingCreated?: never } | 
/**
 *  Records the created (or, for an in-transaction encode retry,
 *  recreated) staging artifact. A repeated `StagingCreated` moves the
 *  journaled pin — which `OutputReady` verifies by file id — to the
 *  recreated file after the failed attempt's adapter cleanup deleted it.
 *  A settled transaction refuses this, so retry-after-abandonment stays
 *  unrepresentable.
 */
({ StagingCreated: {
	run_id: RunId,
	initial: DestructiveIdentity_Deserialize,
} }) & { AbandonStagingIntent?: never; Abandoned?: never; Conflict?: never; OriginalRetired?: never; OutputCommitted?: never; OutputReady?: never; OutputStarted?: never; RetireOriginalIntent?: never } | ({ OutputReady: {
	run_id: RunId,
	staging_identity: ArtifactIdentity_Deserialize,
} }) & { AbandonStagingIntent?: never; Abandoned?: never; Conflict?: never; OriginalRetired?: never; OutputCommitted?: never; OutputStarted?: never; RetireOriginalIntent?: never; StagingCreated?: never } | ({ OutputCommitted: {
	run_id: RunId,
	final_identity: ArtifactIdentity_Deserialize,
} }) & { AbandonStagingIntent?: never; Abandoned?: never; Conflict?: never; OriginalRetired?: never; OutputReady?: never; OutputStarted?: never; RetireOriginalIntent?: never; StagingCreated?: never } | ({ RetireOriginalIntent: {
	run_id: RunId,
} }) & { AbandonStagingIntent?: never; Abandoned?: never; Conflict?: never; OriginalRetired?: never; OutputCommitted?: never; OutputReady?: never; OutputStarted?: never; StagingCreated?: never } | ({ OriginalRetired: {
	run_id: RunId,
} }) & { AbandonStagingIntent?: never; Abandoned?: never; Conflict?: never; OutputCommitted?: never; OutputReady?: never; OutputStarted?: never; RetireOriginalIntent?: never; StagingCreated?: never } | ({ AbandonStagingIntent: {
	run_id: RunId,
	staging_identity: DestructiveIdentity_Deserialize,
} }) & { Abandoned?: never; Conflict?: never; OriginalRetired?: never; OutputCommitted?: never; OutputReady?: never; OutputStarted?: never; RetireOriginalIntent?: never; StagingCreated?: never } | ({ Abandoned: {
	run_id: RunId,
} }) & { AbandonStagingIntent?: never; Conflict?: never; OriginalRetired?: never; OutputCommitted?: never; OutputReady?: never; OutputStarted?: never; RetireOriginalIntent?: never; StagingCreated?: never } | ({ Conflict: {
	run_id: RunId,
	kind: ConflictKind,
	detail: string,
} }) & { AbandonStagingIntent?: never; Abandoned?: never; OriginalRetired?: never; OutputCommitted?: never; OutputReady?: never; OutputStarted?: never; RetireOriginalIntent?: never; StagingCreated?: never };

export type OutputDelta_Serialize = ({ OutputStarted: {
	transaction: OutputTransaction_Serialize,
} }) & { AbandonStagingIntent?: never; Abandoned?: never; Conflict?: never; OriginalRetired?: never; OutputCommitted?: never; OutputReady?: never; RetireOriginalIntent?: never; StagingCreated?: never } | 
/**
 *  Records the created (or, for an in-transaction encode retry,
 *  recreated) staging artifact. A repeated `StagingCreated` moves the
 *  journaled pin — which `OutputReady` verifies by file id — to the
 *  recreated file after the failed attempt's adapter cleanup deleted it.
 *  A settled transaction refuses this, so retry-after-abandonment stays
 *  unrepresentable.
 */
({ StagingCreated: {
	run_id: RunId,
	initial: DestructiveIdentity_Serialize,
} }) & { AbandonStagingIntent?: never; Abandoned?: never; Conflict?: never; OriginalRetired?: never; OutputCommitted?: never; OutputReady?: never; OutputStarted?: never; RetireOriginalIntent?: never } | ({ OutputReady: {
	run_id: RunId,
	staging_identity: ArtifactIdentity_Serialize,
} }) & { AbandonStagingIntent?: never; Abandoned?: never; Conflict?: never; OriginalRetired?: never; OutputCommitted?: never; OutputStarted?: never; RetireOriginalIntent?: never; StagingCreated?: never } | ({ OutputCommitted: {
	run_id: RunId,
	final_identity: ArtifactIdentity_Serialize,
} }) & { AbandonStagingIntent?: never; Abandoned?: never; Conflict?: never; OriginalRetired?: never; OutputReady?: never; OutputStarted?: never; RetireOriginalIntent?: never; StagingCreated?: never } | ({ RetireOriginalIntent: {
	run_id: RunId,
} }) & { AbandonStagingIntent?: never; Abandoned?: never; Conflict?: never; OriginalRetired?: never; OutputCommitted?: never; OutputReady?: never; OutputStarted?: never; StagingCreated?: never } | ({ OriginalRetired: {
	run_id: RunId,
} }) & { AbandonStagingIntent?: never; Abandoned?: never; Conflict?: never; OutputCommitted?: never; OutputReady?: never; OutputStarted?: never; RetireOriginalIntent?: never; StagingCreated?: never } | ({ AbandonStagingIntent: {
	run_id: RunId,
	staging_identity: DestructiveIdentity_Serialize,
} }) & { Abandoned?: never; Conflict?: never; OriginalRetired?: never; OutputCommitted?: never; OutputReady?: never; OutputStarted?: never; RetireOriginalIntent?: never; StagingCreated?: never } | ({ Abandoned: {
	run_id: RunId,
} }) & { AbandonStagingIntent?: never; Conflict?: never; OriginalRetired?: never; OutputCommitted?: never; OutputReady?: never; OutputStarted?: never; RetireOriginalIntent?: never; StagingCreated?: never } | ({ Conflict: {
	run_id: RunId,
	kind: ConflictKind,
	detail: string,
} }) & { AbandonStagingIntent?: never; Abandoned?: never; OriginalRetired?: never; OutputCommitted?: never; OutputReady?: never; OutputStarted?: never; RetireOriginalIntent?: never; StagingCreated?: never };

export type OutputSettings = {
	default_mode: DefaultOutputMode,
	suffix: string,
	separate_folder: string | null,
	overwrite_existing: boolean,
};

export type OutputState = OutputState_Serialize | OutputState_Deserialize;

export type OutputState_Deserialize = "Started" | ({ StagingCreated: {
	initial: DestructiveIdentity_Deserialize,
} }) & { AbandonIntent?: never; Committed?: never; Conflict?: never; Ready?: never; RetireIntent?: never; Retired?: never } | ({ Ready: {
	staging_identity: ArtifactIdentity_Deserialize,
} }) & { AbandonIntent?: never; Committed?: never; Conflict?: never; RetireIntent?: never; Retired?: never; StagingCreated?: never } | ({ Committed: {
	final_identity: ArtifactIdentity_Deserialize,
} }) & { AbandonIntent?: never; Conflict?: never; Ready?: never; RetireIntent?: never; Retired?: never; StagingCreated?: never } | ({ RetireIntent: {
	final_identity: ArtifactIdentity_Deserialize,
} }) & { AbandonIntent?: never; Committed?: never; Conflict?: never; Ready?: never; Retired?: never; StagingCreated?: never } | ({ Retired: {
	final_identity: ArtifactIdentity_Deserialize,
} }) & { AbandonIntent?: never; Committed?: never; Conflict?: never; Ready?: never; RetireIntent?: never; StagingCreated?: never } | ({ AbandonIntent: {
	staging_identity: DestructiveIdentity_Deserialize,
} }) & { Committed?: never; Conflict?: never; Ready?: never; RetireIntent?: never; Retired?: never; StagingCreated?: never } | "Abandoned" | ({ Conflict: {
	kind: ConflictKind,
	detail: string,
} }) & { AbandonIntent?: never; Committed?: never; Ready?: never; RetireIntent?: never; Retired?: never; StagingCreated?: never };

export type OutputState_Serialize = "Started" | ({ StagingCreated: {
	initial: DestructiveIdentity_Serialize,
} }) & { AbandonIntent?: never; Committed?: never; Conflict?: never; Ready?: never; RetireIntent?: never; Retired?: never } | ({ Ready: {
	staging_identity: ArtifactIdentity_Serialize,
} }) & { AbandonIntent?: never; Committed?: never; Conflict?: never; RetireIntent?: never; Retired?: never; StagingCreated?: never } | ({ Committed: {
	final_identity: ArtifactIdentity_Serialize,
} }) & { AbandonIntent?: never; Conflict?: never; Ready?: never; RetireIntent?: never; Retired?: never; StagingCreated?: never } | ({ RetireIntent: {
	final_identity: ArtifactIdentity_Serialize,
} }) & { AbandonIntent?: never; Committed?: never; Conflict?: never; Ready?: never; Retired?: never; StagingCreated?: never } | ({ Retired: {
	final_identity: ArtifactIdentity_Serialize,
} }) & { AbandonIntent?: never; Committed?: never; Conflict?: never; Ready?: never; RetireIntent?: never; StagingCreated?: never } | ({ AbandonIntent: {
	staging_identity: DestructiveIdentity_Serialize,
} }) & { Committed?: never; Conflict?: never; Ready?: never; RetireIntent?: never; Retired?: never; StagingCreated?: never } | "Abandoned" | ({ Conflict: {
	kind: ConflictKind,
	detail: string,
} }) & { AbandonIntent?: never; Committed?: never; Ready?: never; RetireIntent?: never; Retired?: never; StagingCreated?: never };

export type OutputTarget = "Replace" | ({ Suffix: {
	suffix: string,
} }) & { SeparateFolder?: never } | ({ SeparateFolder: {
	directory: string,
	source_root: string | null,
} }) & { Suffix?: never };

export type OutputTransaction = OutputTransaction_Serialize | OutputTransaction_Deserialize;

export type OutputTransaction_Deserialize = {
	run_id: RunId,
	input: string,
	input_identity: DestructiveIdentity_Deserialize,
	staging: string,
	final_path: string,
	final_preimage: DestructiveIdentity_Deserialize | null,
	replacement: Replacement,
	state: OutputState_Deserialize,
};

export type OutputTransaction_Serialize = {
	run_id: RunId,
	input: string,
	input_identity: DestructiveIdentity_Serialize,
	staging: string,
	final_path: string,
	final_preimage: DestructiveIdentity_Serialize | null,
	replacement: Replacement,
	state: OutputState_Serialize,
};

/**
 *  Per-item override of the destination-conflict rule. `FollowSettings`
 *  resolves from the output settings as they stand when the item is claimed;
 *  `Allow` and `Deny` pin the item's behavior regardless of later settings
 *  changes. This is how an `OutputExists` skip becomes resolvable without
 *  touching an active job: edit the item to `Allow` and retry.
 */
export type OverwriteDecision = "FollowSettings" | "Allow" | "Deny";

/**  The decisive standing of an imported history record. */
export type ParkedStatus = "Scanned" | "Analyzed" | "NotWorthwhile" | "Converted";

export type PathBinding = PathBinding_Serialize | PathBinding_Deserialize;

export type PathBinding_Deserialize = {
	/**
	 *  Full identity captured by the stable media observation. Queue and Basic
	 *  Scan freshness compare it exactly and never degrade to size/mtime alone.
	 */
	identity: DestructiveIdentity_Deserialize,
	content_key: ContentKey,
};

export type PathBinding_Serialize = {
	/**
	 *  Full identity captured by the stable media observation. Queue and Basic
	 *  Scan freshness compare it exactly and never degrade to size/mtime alone.
	 */
	identity: DestructiveIdentity_Serialize,
	content_key: ContentKey,
};

export type PathHash = string;

/**
 *  Narrow native-picker intents exposed to the webview. The selected path is
 *  returned without granting general filesystem plugin access.
 */
export type PathPickerKind = "File" | "Files" | "Folder" | "Folders" | "HistoryImport";

/**
 *  How long one job phase ran, measured monotonically by the worker and
 *  delivered in the lossless terminal command — telemetry is never a durable
 *  source.
 */
export type PhaseSpan = {
	phase: JobPhase,
	duration: DurationMs,
};

export type PrivacySettings = {
	anonymize_logs: boolean,
	anonymize_history: boolean,
};

export type QueueItem = {
	id: QueueItemId,
	input: string,
	operation: Operation,
	intent: AnalysisIntent,
	output_target: OutputTarget,
	overwrite: OverwriteDecision,
	state: QueueItemState,
};

/**
 *  A partial edit of a queued item; `None` keeps the current value. The
 *  reducer resolves the full tuple before journaling, so the fold and replay
 *  never see patch semantics.
 */
export type QueueItemEdit = {
	operation: Operation | null,
	intent: AnalysisIntent | null,
	output_target: OutputTarget | null,
	overwrite: OverwriteDecision | null,
};

export type QueueItemId = number;

export type QueueItemState = "Queued" | ({ Reserved: {
	claim_id: ClaimId,
	run_id: RunId,
} }) & { Claimed?: never; Finished?: never; Running?: never } | ({ Claimed: {
	claim_id: ClaimId,
	run_id: RunId,
} }) & { Finished?: never; Reserved?: never; Running?: never } | ({ Running: {
	claim_id: ClaimId,
	run_id: RunId,
} }) & { Claimed?: never; Finished?: never; Reserved?: never } | ({ Finished: ItemOutcome }) & { Claimed?: never; Reserved?: never; Running?: never };

/**  Outcome of a manual update check against the GitHub releases API. */
export type ReleaseSummary = {
	current: string,
	latest: string,
	update_available: boolean,
};

export type Replacement = "KeepOriginal" | "RetireOriginal";

export type ReservedJob = {
	item_id: QueueItemId,
	claim_id: ClaimId,
	run_id: RunId,
	input: string,
	operation: Operation,
	intent: AnalysisIntent,
	output_target: OutputTarget,
};

export type RunId = number;

/**
 *  Terminal run outcomes counted across every conversion run, independent of
 *  the per-content current verdicts.
 */
export type RunTotals = {
	analyzed: number,
	converted: number,
	remuxed: number,
	not_worthwhile: number,
	stopped: number,
	skipped: number,
	failed: number,
};

/**
 *  Outcome of a retroactive log scrub: how many log files were examined, how
 *  many were rewritten with anonymized content, and how many failed.
 */
export type ScrubSummary = {
	total: number,
	modified: number,
	failed: number,
};

export type SearchMeasurement = {
	crf: Crf,
	score: VmafScore,
	predicted_size: number,
	predicted_percent_basis_points: number,
	predicted_duration_ms: number,
	from_cache: boolean,
};

/**
 *  Rolling per-session outcome counters and byte totals. Ephemeral state:
 *  zeroed when a session starts, updated as items finish, never journaled and
 *  never in [`AppSnapshot`] — a reconnecting webview gets the latest value
 *  from the shell's subscribe replay.
 */
export type SessionAggregates = {
	completed: number,
	failed: number,
	skipped: number,
	stopped: number,
	not_worthwhile: number,
	analyzed: number,
	remuxed: number,
	input_bytes: number,
	output_bytes: number,
	encode_duration_ms: number,
};

export type SessionState = "Idle" | "Running" | "StopAfterCurrent" | "ForceStopping";

export type Settings = {
	last_input_folder: string | null,
	scan_extensions: VideoExtension[],
	output: OutputSettings,
	hardware_decode: boolean,
	privacy: PrivacySettings,
	log_folder: string | null,
};

export type ShellEvent = ShellEvent_Serialize | ShellEvent_Deserialize;

export type ShellEvent_Deserialize = {
	seq: number,
	payload: StreamPayload_Deserialize,
};

export type ShellEvent_Serialize = {
	seq: number,
	payload: StreamPayload_Serialize,
};

export type SkipReason = ({ LowResolution: {
	pixels: number,
	minimum: number,
} }) & { AlreadyConverted?: never; NotWorthwhile?: never; ProbableDuplicate?: never } | "AlreadyAv1Matroska" | "OutputExists" | 
/**
 *  Enqueue-time only: the file at the candidate path is recognized by
 *  full destructive identity as the settled output of `source_run` (replace-mode output at
 *  the input path).
 */
({ AlreadyConverted: {
	source_run: RunId | null,
} }) & { LowResolution?: never; NotWorthwhile?: never; ProbableDuplicate?: never } | 
/**
 *  The content's standing verdict says a search already bottomed out at
 *  (or below) the floor this request would try. `source_run: None`: the
 *  verdict was adopted from a history import.
 */
({ NotWorthwhile: {
	source_run: RunId | null,
} }) & { AlreadyConverted?: never; LowResolution?: never; ProbableDuplicate?: never } | 
/**
 *  Claim-time: the observed content carries a Converted/Remuxed verdict —
 *  this file is bytewise identical to content that was already processed,
 *  wherever it now lives. `source_run: None`: the verdict was adopted
 *  from a history import.
 */
({ ProbableDuplicate: {
	source_run: RunId | null,
} }) & { AlreadyConverted?: never; LowResolution?: never; NotWorthwhile?: never } | 
/**
 *  Add-summary only: the path is already queued and not finished. Never a
 *  terminal outcome.
 */
"AlreadyQueued";

/**
 *  The exhaustive Statistics answer. Conversion savings, VMAF, CRF, and time
 *  aggregates cover converted verdicts only; remux facts are counted and
 *  summed separately and never blend into conversion aggregates.
 */
export type StatisticsPayload = {
	/**  The requester-supplied offset the calendar bucketing used. */
	utc_offset_minutes: number,
	converted_files: number,
	/**
	 *  Converted facts that carried both sizes and therefore contribute to
	 *  savings totals, bins, and the cumulative series.
	 */
	sized_converted_files: number,
	remuxed_files: number,
	not_worthwhile_files: number,
	total_input_bytes: number,
	total_output_bytes: number,
	/**  Negative when outputs grew past their inputs overall. */
	total_saved_bytes: number,
	remux_saved_bytes: number,
	/**  Analyzing plus encoding time across converted facts. */
	total_time_ms: number,
	/**  Input gigabytes processed per hour of conversion time. */
	gigabytes_per_hour: number | null,
	reduction_percent: ValueSpread | null,
	vmaf: ValueSpread | null,
	crf: ValueSpread | null,
	/**
	 *  Ten 10%-wide bins over `[0, 100)`; a reduction of exactly 100% (an
	 *  empty output) lands in the last bin.
	 */
	reduction_bins: number[],
	/**
	 *  Converted facts whose output grew — represented here, never clamped
	 *  into the first bin.
	 */
	grew_count: number,
	/**
	 *  Source codecs of converted facts, most frequent first; ties use the
	 *  codec enum's ascending canonical order.
	 */
	codecs: CodecCount[],
	cumulative_savings: CumulativeSavingsPoint[],
	first_epoch_day: number | null,
	last_epoch_day: number | null,
	runs: RunTotals,
};

/**  Core-owned mirror of the adapter's per-stream output byte accounting. */
export type StreamByteSizes = {
	video: number,
	audio: number,
	subtitle: number,
	other: number,
};

export type StreamPayload = StreamPayload_Serialize | StreamPayload_Deserialize;

export type StreamPayload_Deserialize = ({ Snapshot: AppSnapshot_Deserialize }) & { Config?: never; Degraded?: never; Durable?: never; EngineFatal?: never; EngineUnavailable?: never; Ephemeral?: never; SecondInstance?: never } | ({ Durable: DurableDelta_Deserialize }) & { Config?: never; Degraded?: never; EngineFatal?: never; EngineUnavailable?: never; Ephemeral?: never; SecondInstance?: never; Snapshot?: never } | ({ Config: ConfigDelta }) & { Degraded?: never; Durable?: never; EngineFatal?: never; EngineUnavailable?: never; Ephemeral?: never; SecondInstance?: never; Snapshot?: never } | ({ Ephemeral: EphemeralDelta_Deserialize }) & { Config?: never; Degraded?: never; Durable?: never; EngineFatal?: never; EngineUnavailable?: never; SecondInstance?: never; Snapshot?: never } | 
/**
 *  The journal failed replay validation. Reads keep working over the
 *  valid prefix; mutation is rejected until the operator acknowledges
 *  discarding the unreadable tail identified by the report's signature.
 */
({ Degraded: CorruptionReport }) & { Config?: never; Durable?: never; EngineFatal?: never; EngineUnavailable?: never; Ephemeral?: never; SecondInstance?: never; Snapshot?: never } | 
/**
 *  An acknowledged corruption was archived and compacted away; the
 *  journal is a fresh healthy generation and mutation is accepted again.
 */
"Recovered" | 
/**
 *  The engine never started (no data directory, engine start failure);
 *  there is nothing to acknowledge and no commands can run.
 */
({ EngineUnavailable: {
	reason: string,
} }) & { Config?: never; Degraded?: never; Durable?: never; EngineFatal?: never; Ephemeral?: never; SecondInstance?: never; Snapshot?: never } | ({ EngineFatal: {
	message: string,
} }) & { Config?: never; Degraded?: never; Durable?: never; EngineUnavailable?: never; Ephemeral?: never; SecondInstance?: never; Snapshot?: never } | 
/**
 *  Another process holds the engine's data-directory lock: this is a
 *  second instance and the engine refused to start (ADR-008).
 */
({ SecondInstance: {
	lock_path: string,
} }) & { Config?: never; Degraded?: never; Durable?: never; EngineFatal?: never; EngineUnavailable?: never; Ephemeral?: never; Snapshot?: never } | 
/**
 *  The previous run left the crash sentinel behind: it died without a
 *  clean shutdown. Durable state was already restored by the journal
 *  replay; this is informational and stands for the whole run (#33 §12).
 */
"AbnormalShutdown" | 
/**
 *  The user asked to close the window while a session was active. The
 *  shell kept the window open; the frontend owns the prompt and re-issues
 *  the close once the session is idle (#33 §12).
 */
"CloseRequested";

export type StreamPayload_Serialize = ({ Snapshot: AppSnapshot_Serialize }) & { Config?: never; Degraded?: never; Durable?: never; EngineFatal?: never; EngineUnavailable?: never; Ephemeral?: never; SecondInstance?: never } | ({ Durable: DurableDelta_Serialize }) & { Config?: never; Degraded?: never; EngineFatal?: never; EngineUnavailable?: never; Ephemeral?: never; SecondInstance?: never; Snapshot?: never } | ({ Config: ConfigDelta }) & { Degraded?: never; Durable?: never; EngineFatal?: never; EngineUnavailable?: never; Ephemeral?: never; SecondInstance?: never; Snapshot?: never } | ({ Ephemeral: EphemeralDelta_Serialize }) & { Config?: never; Degraded?: never; Durable?: never; EngineFatal?: never; EngineUnavailable?: never; SecondInstance?: never; Snapshot?: never } | 
/**
 *  The journal failed replay validation. Reads keep working over the
 *  valid prefix; mutation is rejected until the operator acknowledges
 *  discarding the unreadable tail identified by the report's signature.
 */
({ Degraded: CorruptionReport }) & { Config?: never; Durable?: never; EngineFatal?: never; EngineUnavailable?: never; Ephemeral?: never; SecondInstance?: never; Snapshot?: never } | 
/**
 *  An acknowledged corruption was archived and compacted away; the
 *  journal is a fresh healthy generation and mutation is accepted again.
 */
"Recovered" | 
/**
 *  The engine never started (no data directory, engine start failure);
 *  there is nothing to acknowledge and no commands can run.
 */
({ EngineUnavailable: {
	reason: string,
} }) & { Config?: never; Degraded?: never; Durable?: never; EngineFatal?: never; Ephemeral?: never; SecondInstance?: never; Snapshot?: never } | ({ EngineFatal: {
	message: string,
} }) & { Config?: never; Degraded?: never; Durable?: never; EngineUnavailable?: never; Ephemeral?: never; SecondInstance?: never; Snapshot?: never } | 
/**
 *  Another process holds the engine's data-directory lock: this is a
 *  second instance and the engine refused to start (ADR-008).
 */
({ SecondInstance: {
	lock_path: string,
} }) & { Config?: never; Degraded?: never; Durable?: never; EngineFatal?: never; EngineUnavailable?: never; Ephemeral?: never; Snapshot?: never } | 
/**
 *  The previous run left the crash sentinel behind: it died without a
 *  clean shutdown. Durable state was already restored by the journal
 *  replay; this is informational and stands for the whole run (#33 §12).
 */
"AbnormalShutdown" | 
/**
 *  The user asked to close the window while a session was active. The
 *  shell kept the window open; the frontend owns the prompt and re-issues
 *  the close once the session is idle (#33 §12).
 */
"CloseRequested";

export type Telemetry = {
	run_id: RunId,
	sequence: number,
	phase: JobPhase,
	progress: JobProgress,
	/**
	 *  Smoothed live throughput in hundredths of a frame per second, from the
	 *  engine's ~3 s sliding window (#33 §11). Absent until the window has a
	 *  sample and for phases with no frame rate (remux) — never a sentinel.
	 */
	fps_centi: number | null,
	/**
	 *  Estimated milliseconds until the current phase completes, from the
	 *  window's progress velocity. Absent during the engine's warm-up and
	 *  whenever the remaining work is unknown (#33 §11) — never a sentinel.
	 */
	eta_ms: number | null,
};

/**
 *  Whether external media tools are usable. Ephemeral state: discovery is a
 *  filesystem fact reported to the reducer, never journaled. Fail-closed by
 *  default so media work stays gated until discovery actually reports.
 */
export type ToolAvailability = ({ Available: {
	source: ToolSource,
	revisions: ToolRevisions,
} }) & { Missing?: never } | ({ Missing: {
	missing: MediaTool[],
	detail: string,
} }) & { Available?: never };

export type ToolRevisions = {
	ab_av1: string,
	ffmpeg: string,
	encoder: string,
};

/**
 *  Which discovery tier produced the active media tools. Precedence is
 *  explicit environment paths, then the managed vendor install, then PATH.
 */
export type ToolSource = "Explicit" | "System" | "Managed";

/**
 *  The full ephemeral tool picture: what is usable, what the vendor pipeline
 *  is doing, and whether the compiled-in manifest is newer than the managed
 *  install. Never journaled; replayed after each snapshot on subscribe.
 */
export type ToolsState = {
	availability: ToolAvailability,
	activity: VendorActivity,
	update_available: boolean,
};

/**
 *  A wall-clock instant in milliseconds since the Unix epoch. Stamped by the
 *  engine (core has no clock) and delivered inside command payloads.
 */
export type UnixMillis = number;

/**  Average and range of one aggregated value; absent when no samples exist. */
export type ValueSpread = {
	average: number | null,
	minimum: number | null,
	maximum: number | null,
	count: number,
};

/**
 *  What the vendor subsystem is doing right now. `Downloading` progress is
 *  throttled by the engine (core has no clock); a terminal `Failed` stands
 *  until the next vendor command replaces it.
 */
export type VendorActivity = "Idle" | "Checking" | ({ Downloading: {
	received: number,
	total: number | null,
} }) & { Failed?: never } | "Installing" | ({ Failed: {
	detail: string,
} }) & { Downloading?: never };

/**
 *  The record's standing judgment about this content: what the latest
 *  decisive run concluded. Distinct from `ItemOutcome` (a run-level fact) —
 *  only Converted, Remuxed, and NotWorthwhile outcomes decide anything about
 *  the content itself. Analyzed results live in `analyses` (facts, not
 *  verdicts); Stopped, Skipped, and Failed decide nothing.
 * 
 *  Lineage is derived, never stored: the runs that concern this content are
 *  `conversion_runs` filtered by `spec.content_key`, ordered by the monotonic
 *  `RunId`. `source_run` links the verdict into that chain.
 */
export type Verdict = {
	kind: VerdictKind,
	/**
	 *  `None`: decided before this app existed — the verdict was adopted
	 *  from a history import and no conversion run backs it.
	 */
	source_run: RunId | null,
	decided_at: UnixMillis,
};

/**
 *  Summary fields only: the full attempt list stays on the run outcome, and
 *  the produced artifact's full identity stays on the settled output
 *  transaction (`outputs[source_run]`). The measured summary (sizes, encode
 *  duration, achieved quality) is absorbed here at fold time so consumers
 *  never branch on provenance; every summary field is nullable because a
 *  history import — and a crash-recovered native success — cannot honestly
 *  supply it.
 */
export type VerdictKind = ({ Converted: {
	/**
	 *  `None`: adopted from a history import — the produced output was
	 *  never content-hashed.
	 */
	output_content_key: ContentKey | null,
	input_size: number | null,
	output_size: number | null,
	encoding_time: DurationMs | null,
	crf: Crf | null,
	vmaf: VmafScore | null,
	target: VmafTarget | null,
} }) & { NotWorthwhile?: never; Remuxed?: never } | ({ Remuxed: {
	/**
	 *  Required: imports never carry remuxes, so every remux verdict
	 *  names a settled, content-hashed output.
	 */
	output_content_key: ContentKey,
	input_size: number | null,
	output_size: number | null,
} }) & { Converted?: never; NotWorthwhile?: never } | ({ NotWorthwhile: {
	requested: VmafTarget,
	floor: VmafTarget,
} }) & { Converted?: never; Remuxed?: never };

export type VideoCodec = "Av1" | "H264" | "Hevc" | "Vp9" | { Other: string };

export type VideoExtension = "mp4" | "mkv" | "avi" | "wmv";

export type VideoMeta = {
	codec: VideoCodec,
	container: MediaContainer,
	width: number,
	height: number,
	rotation_degrees: number,
	duration_ms: number,
	/**
	 *  Byte size of the inspected file — a content fact and the authority for
	 *  input size in views. `PathBinding.identity` is the freshness authority;
	 *  bitrate is derived in views, never stored.
	 */
	size_bytes: number,
	audio: AudioStreamMeta[],
	subtitle_count: number,
};

export type VmafScore = number;

export type VmafTarget = number;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

