// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	subscribe: (channel: Channel<ShellEvent_Deserialize>) => typedError<null, CommandError>(__TAURI_INVOKE("subscribe", { channel })),
	queueAdd: (input: string, operation: Operation, outputTarget: OutputTarget) => typedError<null, CommandError>(__TAURI_INVOKE("queue_add", { input, operation, outputTarget })),
	queueRemove: (itemId: QueueItemId) => typedError<null, CommandError>(__TAURI_INVOKE("queue_remove", { itemId })),
	queueMove: (itemId: QueueItemId, before: number | null) => typedError<null, CommandError>(__TAURI_INVOKE("queue_move", { itemId, before })),
	start: () => typedError<null, CommandError>(__TAURI_INVOKE("start")),
	stopAfterCurrent: () => typedError<null, CommandError>(__TAURI_INVOKE("stop_after_current")),
	forceStop: () => typedError<null, CommandError>(__TAURI_INVOKE("force_stop")),
};

/* Types */
export type AnalysisAttempt = {
	target: VmafTarget,
	last_measurement: SearchMeasurement | null,
};

export type AnalysisProfile = {
	preset: number,
	max_encoded_percent_basis_points: number,
	samples: number | null,
	sample_duration_ms: number,
	thorough: boolean,
	decode_mode: DecodeMode,
	ab_av1_revision: string,
	ffmpeg_revision: string,
	encoder_revision: string,
};

export type AnalysisResult = {
	requested_target: VmafTarget,
	successful_target: VmafTarget,
	fallback_floor: VmafTarget,
	fallback_step: number,
	failed_attempts: AnalysisAttempt[],
	measurement: SearchMeasurement,
	profile: AnalysisProfile,
};

export type AppInfo = {
	version: string,
};

export type ArtifactIdentity = {
	content_key: ContentKey,
	destructive: DestructiveIdentity,
};

export type ClaimId = number;

export type CommandError = {
	code: string,
	message: string,
};

export type ContentKey = string;

export type ConversionRun = {
	spec: JobSpec,
	analysis: AnalysisResult | null,
	output_content_key: ContentKey | null,
	outcome: ItemOutcome | null,
};

export type Crf = number;

export type DecodeMode = "Software" | { Hardware: HardwareDecoder };

export type DecodePreference = "SoftwareOnly" | "HardwarePreferred";

export type DestructiveIdentity = {
	file_id: FileSystemId,
	size: number,
	modified_ns: number | null,
};

export type DurableDelta = ({ QueueAdded: {
	item: QueueItem,
} }) & { AnalysisRecorded?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; QueueMoved?: never; QueueRemoved?: never } | ({ QueueRemoved: {
	item_id: QueueItemId,
} }) & { AnalysisRecorded?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; QueueAdded?: never; QueueMoved?: never } | ({ QueueMoved: {
	item_id: QueueItemId,
	before: QueueItemId | null,
} }) & { AnalysisRecorded?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; QueueAdded?: never; QueueRemoved?: never } | ({ ItemReserved: {
	job: ReservedJob,
} }) & { AnalysisRecorded?: never; ItemFinished?: never; ItemPrepared?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; QueueAdded?: never; QueueMoved?: never; QueueRemoved?: never } | ({ MediaObserved: {
	observation: MediaObservation,
} }) & { AnalysisRecorded?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; Output?: never; QueueAdded?: never; QueueMoved?: never; QueueRemoved?: never } | ({ ItemPrepared: {
	spec: JobSpec,
} }) & { AnalysisRecorded?: never; ItemFinished?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; QueueAdded?: never; QueueMoved?: never; QueueRemoved?: never } | ({ ItemRunning: {
	item_id: QueueItemId,
	claim_id: ClaimId,
	run_id: RunId,
} }) & { AnalysisRecorded?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; MediaObserved?: never; Output?: never; QueueAdded?: never; QueueMoved?: never; QueueRemoved?: never } | ({ AnalysisRecorded: {
	run_id: RunId,
	result: AnalysisResult,
} }) & { ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; QueueAdded?: never; QueueMoved?: never; QueueRemoved?: never } | ({ ItemFinished: {
	item_id: QueueItemId,
	claim_id: ClaimId,
	run_id: RunId,
	outcome: ItemOutcome,
} }) & { AnalysisRecorded?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; Output?: never; QueueAdded?: never; QueueMoved?: never; QueueRemoved?: never } | ({ Output: OutputDelta }) & { AnalysisRecorded?: never; ItemFinished?: never; ItemPrepared?: never; ItemReserved?: never; ItemRunning?: never; MediaObserved?: never; QueueAdded?: never; QueueMoved?: never; QueueRemoved?: never };

export type DurableState = DurableState_Serialize | DurableState_Deserialize;

export type DurableState_Deserialize = {
	queue: QueueItem[],
	paths: { [key in PathHash]: PathBinding },
	records: { [key in ContentKey]: FileRecord_Deserialize },
	outputs: { [key in RunId]: OutputTransaction },
	conversion_runs: { [key in RunId]: ConversionRun },
};

export type DurableState_Serialize = {
	queue: QueueItem[],
	paths: { [key in PathHash]: PathBinding },
	records: { [key in ContentKey]: FileRecord_Serialize },
	outputs: { [key in RunId]: OutputTransaction },
	conversion_runs: { [key in RunId]: ConversionRun },
};

export type EphemeralDelta = ({ SessionChanged: SessionState }) & { CommandRejected?: never; Telemetry?: never; TelemetryCleared?: never; WorkerCrashed?: never } | ({ Telemetry: Telemetry }) & { CommandRejected?: never; SessionChanged?: never; TelemetryCleared?: never; WorkerCrashed?: never } | ({ TelemetryCleared: {
	run_id: RunId,
} }) & { CommandRejected?: never; SessionChanged?: never; Telemetry?: never; WorkerCrashed?: never } | ({ WorkerCrashed: {
	message: string,
} }) & { CommandRejected?: never; SessionChanged?: never; Telemetry?: never; TelemetryCleared?: never } | ({ CommandRejected: {
	reason: string,
} }) & { SessionChanged?: never; Telemetry?: never; TelemetryCleared?: never; WorkerCrashed?: never };

export type ExecutionSettings = {
	requested_target: VmafTarget,
	fallback_floor: VmafTarget,
	fallback_step: number,
	overwrite_existing: boolean,
	decode_preference: DecodePreference,
	profile: AnalysisProfile,
};

export type FileRecord = FileRecord_Serialize | FileRecord_Deserialize;

export type FileRecord_Deserialize = {
	metadata: VideoMeta,
	analyses: ([AnalysisProfile, { [key in VmafTarget]: AnalysisResult }])[],
};

export type FileRecord_Serialize = {
	metadata: VideoMeta,
	analyses: ([AnalysisProfile, { [key in VmafTarget]: AnalysisResult }])[],
};

export type FileStamp = {
	size: number,
	modified_ns: number | null,
};

export type FileSystemId = ({ Unix: {
	device: number,
	inode: number,
} }) & { WindowsHighResolution?: never; WindowsLowResolution?: never } | ({ WindowsLowResolution: {
	volume_serial: number,
	file_index: number,
} }) & { Unix?: never; WindowsHighResolution?: never } | ({ WindowsHighResolution: {
	volume_serial: number,
	file_id: number,
} }) & { Unix?: never; WindowsLowResolution?: never };

export type HardwareDecoder = "H264Cuvid" | "H264Qsv" | "HevcCuvid" | "HevcQsv" | "Vp9Cuvid" | "Vp9Qsv" | "Av1Cuvid" | "Av1Qsv";

export type ItemOutcome = "Analyzed" | "Converted" | "Remuxed" | ({ NotWorthwhile: {
	attempts: AnalysisAttempt[],
} }) & { Failed?: never; Skipped?: never } | "Stopped" | ({ Skipped: {
	reason: SkipReason,
} }) & { Failed?: never; NotWorthwhile?: never } | ({ Failed: {
	message: string,
} }) & { NotWorthwhile?: never; Skipped?: never };

export type JobAction = ({ Analyze: {
	selected_analysis: AnalysisResult | null,
} }) & { Encode?: never; Skip?: never } | ({ Encode: {
	selected_analysis: AnalysisResult | null,
} }) & { Analyze?: never; Skip?: never } | "Remux" | ({ Skip: {
	reason: SkipReason,
} }) & { Analyze?: never; Encode?: never };

export type JobPhase = "Preparing" | "Analyzing" | "Encoding" | "Verifying" | "Finalizing";

export type JobProgress = "Phase" | ({ SearchBasisPoints: number }) & { OutputPositionMs?: never } | ({ OutputPositionMs: number }) & { SearchBasisPoints?: never };

export type JobSpec = {
	item_id: QueueItemId,
	claim_id: ClaimId,
	run_id: RunId,
	input: string,
	content_key: ContentKey | null,
	operation: Operation,
	output_target: OutputTarget,
	execution: ExecutionSettings,
	action: JobAction,
};

export type MediaContainer = "Matroska" | { Other: string };

export type MediaObservation = {
	path_hash: PathHash,
	binding: PathBinding,
	metadata: VideoMeta,
};

export type Operation = "Analyze" | "Convert";

export type OutputDelta = ({ OutputStarted: {
	transaction: OutputTransaction,
} }) & { AbandonStagingIntent?: never; Abandoned?: never; Conflict?: never; OriginalRetired?: never; OutputCommitted?: never; OutputReady?: never; RetireOriginalIntent?: never } | ({ OutputReady: {
	run_id: RunId,
	staging_identity: ArtifactIdentity,
} }) & { AbandonStagingIntent?: never; Abandoned?: never; Conflict?: never; OriginalRetired?: never; OutputCommitted?: never; OutputStarted?: never; RetireOriginalIntent?: never } | ({ OutputCommitted: {
	run_id: RunId,
	final_identity: ArtifactIdentity,
} }) & { AbandonStagingIntent?: never; Abandoned?: never; Conflict?: never; OriginalRetired?: never; OutputReady?: never; OutputStarted?: never; RetireOriginalIntent?: never } | ({ RetireOriginalIntent: {
	run_id: RunId,
} }) & { AbandonStagingIntent?: never; Abandoned?: never; Conflict?: never; OriginalRetired?: never; OutputCommitted?: never; OutputReady?: never; OutputStarted?: never } | ({ OriginalRetired: {
	run_id: RunId,
} }) & { AbandonStagingIntent?: never; Abandoned?: never; Conflict?: never; OutputCommitted?: never; OutputReady?: never; OutputStarted?: never; RetireOriginalIntent?: never } | ({ AbandonStagingIntent: {
	run_id: RunId,
	staging_identity: DestructiveIdentity,
} }) & { Abandoned?: never; Conflict?: never; OriginalRetired?: never; OutputCommitted?: never; OutputReady?: never; OutputStarted?: never; RetireOriginalIntent?: never } | ({ Abandoned: {
	run_id: RunId,
} }) & { AbandonStagingIntent?: never; Conflict?: never; OriginalRetired?: never; OutputCommitted?: never; OutputReady?: never; OutputStarted?: never; RetireOriginalIntent?: never } | ({ Conflict: {
	run_id: RunId,
	reason: string,
} }) & { AbandonStagingIntent?: never; Abandoned?: never; OriginalRetired?: never; OutputCommitted?: never; OutputReady?: never; OutputStarted?: never; RetireOriginalIntent?: never };

export type OutputState = "Started" | ({ Ready: {
	staging_identity: ArtifactIdentity,
} }) & { AbandonIntent?: never; Committed?: never; Conflict?: never; RetireIntent?: never; Retired?: never } | ({ Committed: {
	final_identity: ArtifactIdentity,
} }) & { AbandonIntent?: never; Conflict?: never; Ready?: never; RetireIntent?: never; Retired?: never } | ({ RetireIntent: {
	final_identity: ArtifactIdentity,
} }) & { AbandonIntent?: never; Committed?: never; Conflict?: never; Ready?: never; Retired?: never } | ({ Retired: {
	final_identity: ArtifactIdentity,
} }) & { AbandonIntent?: never; Committed?: never; Conflict?: never; Ready?: never; RetireIntent?: never } | ({ AbandonIntent: {
	staging_identity: DestructiveIdentity,
} }) & { Committed?: never; Conflict?: never; Ready?: never; RetireIntent?: never; Retired?: never } | "Abandoned" | ({ Conflict: {
	reason: string,
} }) & { AbandonIntent?: never; Committed?: never; Ready?: never; RetireIntent?: never; Retired?: never };

export type OutputTarget = "Replace" | ({ Suffix: {
	suffix: string,
} }) & { SeparateFolder?: never } | ({ SeparateFolder: {
	directory: string,
	source_root: string | null,
} }) & { Suffix?: never };

export type OutputTransaction = {
	run_id: RunId,
	input: string,
	input_identity: DestructiveIdentity,
	staging: string,
	initial_staging_identity: DestructiveIdentity,
	final_path: string,
	final_preimage: DestructiveIdentity | null,
	replacement: Replacement,
	state: OutputState,
};

export type PathBinding = {
	stamp: FileStamp,
	content_key: ContentKey,
};

export type PathHash = string;

export type QueueItem = {
	id: QueueItemId,
	input: string,
	operation: Operation,
	output_target: OutputTarget,
	state: QueueItemState,
};

export type QueueItemId = number;

export type QueueItemState = "Queued" | ({ Reserved: {
	claim_id: ClaimId,
	run_id: RunId,
} }) & { Claimed?: never; Finished?: never; Running?: never } | ({ Claimed: {
	claim_id: ClaimId,
	run_id: RunId,
} }) & { Finished?: never; Reserved?: never; Running?: never } | ({ Running: {
	claim_id: ClaimId,
	run_id: RunId,
} }) & { Claimed?: never; Finished?: never; Reserved?: never } | ({ Finished: ItemOutcome }) & { Claimed?: never; Reserved?: never; Running?: never };

export type Replacement = "KeepOriginal" | "RetireOriginal";

export type ReservedJob = {
	item_id: QueueItemId,
	claim_id: ClaimId,
	run_id: RunId,
	input: string,
	operation: Operation,
	output_target: OutputTarget,
};

export type RunId = number;

export type SearchMeasurement = {
	crf: Crf,
	score: VmafScore,
	predicted_size: number,
	predicted_percent_basis_points: number,
	predicted_duration_ms: number,
	from_cache: boolean,
};

export type SessionState = "Idle" | "Running" | "StopAfterCurrent" | "ForceStopping";

export type ShellEvent = ShellEvent_Serialize | ShellEvent_Deserialize;

export type ShellEvent_Deserialize = {
	seq: number,
	payload: StreamPayload_Deserialize,
};

export type ShellEvent_Serialize = {
	seq: number,
	payload: StreamPayload_Serialize,
};

export type SkipReason = { LowResolution: {
	pixels: number,
	minimum: number,
} } | "AlreadyAv1Matroska" | "OutputExists";

export type StreamPayload = StreamPayload_Serialize | StreamPayload_Deserialize;

export type StreamPayload_Deserialize = ({ Snapshot: DurableState_Deserialize }) & { Degraded?: never; Durable?: never; EngineFatal?: never; Ephemeral?: never } | ({ Durable: DurableDelta }) & { Degraded?: never; EngineFatal?: never; Ephemeral?: never; Snapshot?: never } | ({ Ephemeral: EphemeralDelta }) & { Degraded?: never; Durable?: never; EngineFatal?: never; Snapshot?: never } | ({ Degraded: {
	reason: string,
} }) & { Durable?: never; EngineFatal?: never; Ephemeral?: never; Snapshot?: never } | ({ EngineFatal: {
	message: string,
} }) & { Degraded?: never; Durable?: never; Ephemeral?: never; Snapshot?: never };

export type StreamPayload_Serialize = ({ Snapshot: DurableState_Serialize }) & { Degraded?: never; Durable?: never; EngineFatal?: never; Ephemeral?: never } | ({ Durable: DurableDelta }) & { Degraded?: never; EngineFatal?: never; Ephemeral?: never; Snapshot?: never } | ({ Ephemeral: EphemeralDelta }) & { Degraded?: never; Durable?: never; EngineFatal?: never; Snapshot?: never } | ({ Degraded: {
	reason: string,
} }) & { Durable?: never; EngineFatal?: never; Ephemeral?: never; Snapshot?: never } | ({ EngineFatal: {
	message: string,
} }) & { Degraded?: never; Durable?: never; Ephemeral?: never; Snapshot?: never };

export type Telemetry = {
	run_id: RunId,
	sequence: number,
	phase: JobPhase,
	progress: JobProgress,
};

export type VideoCodec = "Av1" | "H264" | "Hevc" | "Vp9" | { Other: string };

export type VideoMeta = {
	codec: VideoCodec,
	container: MediaContainer,
	width: number,
	height: number,
	rotation_degrees: number,
	duration_ms: number,
};

export type VmafScore = number;

export type VmafTarget = number;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

